/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Evolve_3D_logo_updated.glb");

  return (
    <group {...props} scale={2.2} dispose={null}>
      <mesh
        geometry={nodes.Curve.geometry}
        material={materials["Material.001"]}
        position={[0, 0.21, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Evolve_3D_logo_updated.glb");
